I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/season_03.rpy", line 846, in script
    $ s3_amount_npcs_like_mc['AJ'] += 1
  File "game/season_03.rpy", line 846, in <module>
    $ s3_amount_npcs_like_mc['AJ'] += 1
NameError: name 's3e1p1_strongest_couple' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/season_03.rpy", line 846, in script
    $ s3_amount_npcs_like_mc['AJ'] += 1
  File "C:\Users\larsa\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\larsa\Documents\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\larsa\Documents\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/season_03.rpy", line 846, in <module>
    $ s3_amount_npcs_like_mc['AJ'] += 1
NameError: name 's3e1p1_strongest_couple' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Love Island the Game: Remastered 1.0
Fri Jan 26 23:24:55 2024
